# Generated by Django 4.1.1 on 2023-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.CharField(
                choices=[("buyer", "buyer"), ("staff_member", "staff_member")],
                default="buyer",
                max_length=12,
            ),
        ),
    ]
