# Generated by Django 4.1.1 on 2023-07-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0004_rename_staff_user_agency_staff"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="agency_staff",),
        migrations.AddField(
            model_name="user",
            name="user_status",
            field=models.CharField(
                choices=[("customer", "customer"), ("staff", "staff")],
                default="customer",
                max_length=12,
            ),
        ),
    ]
