# Generated by Django 4.1.1 on 2023-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0006_alter_user_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="code", field=models.CharField(max_length=4),
        ),
    ]
