# Generated by Django 4.1.1 on 2023-07-19 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0008_alter_user_code_user_registration_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_registration_timestamp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timestamp",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
