# Generated by Django 4.1.1 on 2023-07-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0009_alter_user_registration_timestamp_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Bus_Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=20)),
                ("address_details", models.CharField(max_length=20)),
                ("price", models.IntegerField(default=0)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "record_status",
                    models.CharField(
                        choices=[("actual", "actual"), ("deprecated", "deprecated")],
                        default="actual",
                        max_length=12,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops",
                        to="ad_bus_stops.city",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
