# Generated by Django 4.1.1 on 2023-07-20 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0010_city_bus_stop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_stop_datetime", models.CharField(max_length=100, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preemption",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
