# Generated by Django 4.1.1 on 2023-07-20 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0013_alter_current_order_ad_removal_de_facto_recorded_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders_Archived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("exposition_started", models.DateField()),
                ("exposition_ended", models.DateField()),
                (
                    "order_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("successfully completed", "successfully completed"),
                            ("canceled for non-payment", "canceled for non-payment"),
                            ("canceled by staff", "canceled by staff"),
                        ],
                        max_length=24,
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                ("datetime_of_initial_order", models.DateTimeField()),
                ("datetime_of_payment_recording", models.DateTimeField(blank=True)),
                (
                    "datetime_of_exposition_de_facto_recording",
                    models.DateTimeField(blank=True),
                ),
                (
                    "datetime_of_ad_removal_de_facto_recording",
                    models.DateTimeField(blank=True),
                ),
                ("initial_order_id", models.IntegerField(unique=True)),
                (
                    "ad_removal_de_facto_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_removal_de_facto_recorded_orders_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_canceled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exposition_de_facto_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposition_de_facto_recorded_orders_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_recorded_orders_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Current_Order",),
    ]
