# Generated by Django 4.1.1 on 2023-07-20 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0015_current_order_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="current_order",
            name="ad_removal_de_facto_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_removal_de_facto_recorded_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="current_order",
            name="datetime_of_ad_removal_de_facto_recording",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="current_order",
            name="datetime_of_exposition_de_facto_recording",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="current_order",
            name="datetime_of_payment_recording",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="current_order",
            name="exposition_de_facto_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exposition_de_facto_recorded_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="current_order",
            name="payment_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_recorded_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orders_archived",
            name="ad_removal_de_facto_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_removal_de_facto_recorded_orders_a",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orders_archived",
            name="canceled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_canceled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orders_archived",
            name="datetime_of_ad_removal_de_facto_recording",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orders_archived",
            name="datetime_of_exposition_de_facto_recording",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orders_archived",
            name="datetime_of_payment_recording",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orders_archived",
            name="exposition_de_facto_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exposition_de_facto_recorded_orders_a",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orders_archived",
            name="order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("successfully completed", "successfully completed"),
                    ("canceled for non-payment", "canceled for non-payment"),
                    ("canceled by staff", "canceled by staff"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orders_archived",
            name="payment_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_recorded_orders_a",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
