# Generated by Django 4.1.1 on 2023-07-20 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0016_alter_current_order_ad_removal_de_facto_recorded_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Previous_update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SetUp_Parameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_status",
                    models.CharField(
                        choices=[("actual", "actual"), ("deprecated", "deprecated")],
                        default="actual",
                        max_length=12,
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("payment_waiting", models.IntegerField(default=5)),
                ("preparation", models.IntegerField(default=3)),
                ("duration1", models.IntegerField(default=2)),
                ("duration2", models.IntegerField(default=3)),
                ("duration3", models.IntegerField(default=4)),
                ("discount1", models.IntegerField(default=10)),
                ("discount2", models.IntegerField(default=20)),
                ("discount3", models.IntegerField(default=30)),
                ("year", models.IntegerField(default=2025)),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_up_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference_Archived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_price", models.IntegerField(default=0)),
                (
                    "bus_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_orders",
                        to="ad_bus_stops.bus_stop",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops_used",
                        to="ad_bus_stops.orders_archived",
                    ),
                ),
            ],
        ),
    ]
