# Generated by Django 4.1.1 on 2023-07-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0017_previous_update_setup_parameters_reference_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_to_Remove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_remove",
                        to="ad_bus_stops.current_order",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_to_Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_place",
                        to="ad_bus_stops.current_order",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
