# Generated by Django 4.1.1 on 2023-07-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0018_order_to_remove_order_to_place"),
    ]

    operations = [
        migrations.RemoveField(model_name="order_to_remove", name="order",),
        migrations.DeleteModel(name="Order_to_Place",),
        migrations.DeleteModel(name="Order_to_Remove",),
    ]
