# Generated by Django 4.1.1 on 2023-07-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0019_remove_order_to_remove_order_delete_order_to_place_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_to_Remove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ad_bus_stops.current_order",
                    ),
                ),
            ],
        ),
    ]
