# Generated by Django 4.1.1 on 2023-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0023_project_check_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Study_Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10, unique=True)),
                ("password", models.CharField(default="", max_length=10)),
                ("creation_date", models.DateField(auto_now_add=True)),
                (
                    "previous_date_selected_as_today",
                    models.DateField(auto_now_add=True),
                ),
            ],
        ),
        migrations.DeleteModel(name="Project_Check_Account",),
    ]
