# Generated by Django 4.1.1 on 2023-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0024_study_account_delete_project_check_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="App_Explorer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10, unique=True)),
                ("password", models.CharField(default="", max_length=10)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("current_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(name="Study_Account",),
    ]
