# Generated by Django 4.1.1 on 2023-07-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0026_app_explorer_show_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="app_explorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_customers",
                to="ad_bus_stops.app_explorer",
            ),
        ),
    ]
