# Generated by Django 4.1.1 on 2023-07-26 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0027_user_app_explorer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preemption",
            old_name="bus_stop_datetime",
            new_name="bus_stop_id_month_year",
        ),
        migrations.RemoveField(model_name="bus_stop", name="datetime",),
        migrations.AddField(
            model_name="bus_stop",
            name="app_explorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_stops_recorded",
                to="ad_bus_stops.app_explorer",
            ),
        ),
        migrations.AddField(
            model_name="bus_stop",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus_stop",
            name="former_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="app_explorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities_recorded",
                to="ad_bus_stops.app_explorer",
            ),
        ),
        migrations.AddField(
            model_name="preemption",
            name="app_explorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preemptions",
                to="ad_bus_stops.app_explorer",
            ),
        ),
        migrations.AlterField(
            model_name="bus_stop",
            name="staff_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_stops_edited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
