# Generated by Django 4.1.1 on 2023-07-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0028_rename_bus_stop_datetime_preemption_bus_stop_id_month_year_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="user_status", new_name="status",
        ),
    ]
