# Generated by Django 4.1.1 on 2023-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0029_rename_user_status_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
