# Generated by Django 4.1.1 on 2023-07-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0030_alter_city_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_stop", name="price", field=models.IntegerField(default=100),
        ),
    ]
