# Generated by Django 4.1.1 on 2023-07-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0031_alter_bus_stop_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bus_stop", old_name="address_details", new_name="house",
        ),
    ]
