# Generated by Django 4.1.1 on 2023-07-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0032_rename_address_details_bus_stop_house"),
    ]

    operations = [
        migrations.RemoveField(model_name="reference", name="bus_stop",),
        migrations.RemoveField(model_name="reference", name="order",),
        migrations.RemoveField(model_name="reference_archived", name="bus_stop",),
        migrations.RemoveField(model_name="reference_archived", name="order",),
        migrations.DeleteModel(name="Bus_Stop",),
        migrations.DeleteModel(name="Reference",),
        migrations.DeleteModel(name="Reference_Archived",),
    ]
