# Generated by Django 4.1.1 on 2023-07-28 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0033_remove_reference_bus_stop_remove_reference_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus_Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=20)),
                ("house", models.CharField(max_length=20)),
                ("price", models.IntegerField(default=100)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "record_status",
                    models.CharField(
                        choices=[("actual", "actual"), ("deprecated", "deprecated")],
                        default="actual",
                        max_length=12,
                    ),
                ),
                ("former_id", models.IntegerField(blank=True, null=True)),
                (
                    "app_explorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops_recorded",
                        to="ad_bus_stops.app_explorer",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops",
                        to="ad_bus_stops.city",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference_Archived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_price", models.IntegerField(default=0)),
                (
                    "bus_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_orders",
                        to="ad_bus_stops.bus_stop",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops_used",
                        to="ad_bus_stops.orders_archived",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_price", models.IntegerField(default=0)),
                (
                    "bus_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_orders",
                        to="ad_bus_stops.bus_stop",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops_booked",
                        to="ad_bus_stops.current_order",
                    ),
                ),
            ],
        ),
    ]
