# Generated by Django 4.1.1 on 2023-07-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0034_bus_stop_reference_archived_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="current_order", name="ad_removal_de_facto_recorded_by",
        ),
        migrations.RemoveField(
            model_name="current_order", name="exposition_de_facto_recorded_by",
        ),
        migrations.RemoveField(model_name="current_order", name="payment_recorded_by",),
        migrations.RemoveField(model_name="current_order", name="user",),
        migrations.RemoveField(model_name="letter", name="recipient",),
        migrations.RemoveField(model_name="letter", name="sender",),
        migrations.RemoveField(model_name="order_to_place", name="order",),
        migrations.RemoveField(model_name="order_to_remove", name="order",),
        migrations.RemoveField(
            model_name="orders_archived", name="ad_removal_de_facto_recorded_by",
        ),
        migrations.RemoveField(model_name="orders_archived", name="canceled_by",),
        migrations.RemoveField(
            model_name="orders_archived", name="exposition_de_facto_recorded_by",
        ),
        migrations.RemoveField(
            model_name="orders_archived", name="payment_recorded_by",
        ),
        migrations.RemoveField(model_name="orders_archived", name="user",),
        migrations.RemoveField(model_name="preemption", name="app_explorer",),
        migrations.RemoveField(model_name="preemption", name="user",),
        migrations.DeleteModel(name="Previous_update",),
        migrations.RemoveField(model_name="reference", name="bus_stop",),
        migrations.RemoveField(model_name="reference", name="order",),
        migrations.RemoveField(model_name="reference_archived", name="bus_stop",),
        migrations.RemoveField(model_name="reference_archived", name="order",),
        migrations.RemoveField(model_name="setup_parameters", name="staff_member",),
        migrations.DeleteModel(name="Current_Order",),
        migrations.DeleteModel(name="Letter",),
        migrations.DeleteModel(name="Order_to_Place",),
        migrations.DeleteModel(name="Order_to_Remove",),
        migrations.DeleteModel(name="Orders_Archived",),
        migrations.DeleteModel(name="Preemption",),
        migrations.DeleteModel(name="Reference",),
        migrations.DeleteModel(name="Reference_Archived",),
        migrations.DeleteModel(name="SetUp_Parameters",),
    ]
