# Generated by Django 4.1.1 on 2023-07-29 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0038_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders_Archived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "order_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("successfully completed", "successfully completed"),
                            ("canceled for non-payment", "canceled for non-payment"),
                            ("canceled by staff", "canceled by staff"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("initial_order_id", models.IntegerField(unique=True)),
                ("exposition_started", models.DateField()),
                ("exposition_ended", models.DateField()),
                ("total_sum", models.IntegerField(default=0)),
                ("date_of_initial_order", models.DateField()),
                (
                    "datetime_of_payment_recording",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "datetime_of_exposition_de_facto_recording",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "datetime_of_ad_removal_de_facto_recording",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "ad_removal_de_facto_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_removal_de_facto_recorded_orders_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "app_explorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_archived",
                        to="ad_bus_stops.app_explorer",
                    ),
                ),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_canceled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exposition_de_facto_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposition_de_facto_recorded_orders_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_recorded_orders_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference_Archived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_price", models.IntegerField(default=0)),
                (
                    "bus_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_orders",
                        to="ad_bus_stops.bus_stop",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops_used",
                        to="ad_bus_stops.orders_archived",
                    ),
                ),
            ],
        ),
    ]
