# Generated by Django 4.1.1 on 2023-07-29 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0039_orders_archived_reference_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulated_World_Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("date_explorer", models.CharField(max_length=20, unique=True)),
                (
                    "app_explorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sim_w_update",
                        to="ad_bus_stops.app_explorer",
                    ),
                ),
            ],
        ),
    ]
