# Generated by Django 4.1.1 on 2023-07-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0040_simulated_world_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="Last_Explorer_Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
