# Generated by Django 4.1.1 on 2023-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0043_order_to_remove_order_to_place_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app_explorer",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
    ]
