# Generated by Django 4.1.1 on 2023-07-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0044_alter_app_explorer_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_stop",
            name="app_explorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_stops_recorded",
                to="ad_bus_stops.app_explorer",
            ),
        ),
    ]
