# Generated by Django 4.1.1 on 2023-08-01 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0046_alter_bus_stop_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setup_parameters",
            name="app_explorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setup_parameters",
                to="ad_bus_stops.app_explorer",
            ),
        ),
        migrations.AlterField(
            model_name="setup_parameters",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="setup_parameters",
            name="staff_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_up_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
