# Generated by Django 4.1.1 on 2023-08-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0047_alter_setup_parameters_app_explorer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="SetUp_Parameters",),
    ]
