# Generated by Django 4.1.1 on 2023-08-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0049_setup_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app_explorer", name="creation_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="app_explorer", name="current_date", field=models.DateField(),
        ),
    ]
