# Generated by Django 4.1.1 on 2023-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0050_alter_app_explorer_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setup_parameters",
            name="year",
            field=models.IntegerField(default=2026),
        ),
    ]
