# Generated by Django 4.1.1 on 2023-08-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0051_alter_setup_parameters_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="current_order", name="datetime_of_payment_recording",
        ),
        migrations.AddField(
            model_name="current_order",
            name="date_of_payment_recording",
            field=models.DateField(blank=True, null=True),
        ),
    ]
