# Generated by Django 4.1.1 on 2023-08-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0053_remove_current_order_datetime_of_ad_removal_de_facto_recording_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="current_order",
            name="payment_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_recorded_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
