# Generated by Django 4.1.1 on 2023-08-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0056_alter_current_order_current_exposition_de_facto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders_archived",
            old_name="date_of_initial_order",
            new_name="first_booking_date",
        ),
    ]
