# Generated by Django 4.1.1 on 2023-08-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0057_rename_date_of_initial_order_orders_archived_first_booking_date",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders_archived",
            old_name="exposition_ended",
            new_name="exposition_ends",
        ),
        migrations.RenameField(
            model_name="orders_archived",
            old_name="exposition_started",
            new_name="exposition_starts",
        ),
    ]
