# Generated by Django 4.1.1 on 2023-08-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0058_rename_exposition_ended_orders_archived_exposition_ends_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="order_to_remove", name="order",),
        migrations.DeleteModel(name="Order_to_Place",),
        migrations.DeleteModel(name="Order_to_Remove",),
    ]
