# Generated by Django 4.1.1 on 2023-08-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ad_bus_stops",
            "0059_remove_order_to_remove_order_delete_order_to_place_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulated_world_update", name="date_explorer",
        ),
    ]
