# Generated by Django 4.1.1 on 2023-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0060_remove_simulated_world_update_date_explorer"),
    ]

    operations = [
        migrations.DeleteModel(name="Reference_Archived",),
    ]
