# Generated by Django 4.1.1 on 2023-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_bus_stops", "0062_reference_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="current_order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("cart", "cart"),
                    ("payment waiting", "payment waiting"),
                    ("Paid. Exposition awaiting", "Paid. Exposition awaiting"),
                    ("current exposition de jure", "current exposition de jure"),
                    ("end of exposition de jure", "end of exposition de jure"),
                ],
                default="cart",
                max_length=26,
            ),
        ),
    ]
